### ISSUE TITLE
甚至上传了.DS_Store嘲讽mac😂😂😂

### ISSUE THREAD

**Issue by ChengranAA** [Lakr233/SafariYYDS#15]

**Comment by Lakr233** [comment]
你是故意的还是不小心的？

<img width="541" alt="截屏2023-03-01 07 06 33" src="https://user-images.githubusercontent.com/25259084/222002927-1353f9d2-8baf-4e5a-a945-5d76e80d3633.png">

**Comment by ChengranAA** [comment]
不小心，不小心～
